[package]
name = "login_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
authentication = { path = "../authentication" }
# cargo add clap -F derive 
clap = { version = "4.5.4", features = ["derive"] }
